import { ArrowUpRight, Check, Clock3, Cpu, Download, FileCheck2, Gauge, Search, ShieldCheck, Thermometer, Zap } from "lucide-react";

type SectionName = "Live test" | "Test history" | "MCB database" | "Reports" | "Analytics" | "Alerts" | "AI inspector" | "Device / ESP32";

const sectionDetails: Record<SectionName, { kicker: string; title: string; description: string }> = {
  "Live test": { kicker: "Test engine / simulation", title: "Run a controlled test", description: "Configure the profile, verify the pre-flight gate, and observe the deterministic telemetry stream." },
  "Test history": { kicker: "Traceability / sessions", title: "Test history", description: "Search persisted sessions by unit, batch, profile, or verdict." },
  "MCB database": { kicker: "Catalog / test profiles", title: "MCB database", description: "Rated devices, curve types, and versioned test envelopes used by the bench." },
  Reports: { kicker: "Evidence / exports", title: "Reports", description: "Generate a report from persisted test data and keep the demonstration boundary visible." },
  Analytics: { kicker: "Quality / trends", title: "Analytics", description: "Read pass rate, latency, and batch drift without losing the underlying test evidence." },
  Alerts: { kicker: "Safety / attention queue", title: "Alerts", description: "Resolve device, sensor, and test exceptions before they become a blocked run." },
  "AI inspector": { kicker: "Advisory / evidence", title: "AI inspector", description: "Review structured anomaly evidence. The deterministic rule engine remains the official verdict." },
  "Device / ESP32": { kicker: "Gateway / sensors", title: "Device health", description: "Inspect the simulated gateway, sensor readiness, and the boundary before hardware is connected." },
};

export function SectionView({ section }: { section: SectionName }) {
  const details = sectionDetails[section];

  return <section className="section-view"><div className="section-view-head"><div><div className="section-kicker"><span>{details.kicker}</span><span className="section-mode">SIMULATION</span></div><h2>{details.title}</h2><p>{details.description}</p></div><div className="section-view-actions"><button className="outline-control"><Search size={14} /> Search</button><button className="blue-control"><ArrowUpRight size={14} /> Open workflow</button></div></div>{section === "Live test" && <LiveTestView />}{section === "Test history" && <HistoryView />}{section === "MCB database" && <CatalogView />}{section === "Reports" && <ReportsView />}{section === "Analytics" && <AnalyticsView />}{section === "Alerts" && <AlertsView />}{section === "AI inspector" && <InspectorView />}{section === "Device / ESP32" && <DeviceView />}</section>;
}

function LiveTestView() { return <div className="section-columns"><div className="workflow-board"><div className="workflow-top"><span>SIM-0143</span><span className="workflow-state"><span className="signal-dot" /> PRECHECK READY</span></div><div className="live-metric-large"><span>Target current</span><strong>23.2 <em>A</em></strong><small>1.45 × In · Acti9 iC60N / 16A</small></div><div className="workflow-bars"><WorkflowStep label="Fixture & interlock" status="PASSED" /><WorkflowStep label="Current sensor" status="PASSED" /><WorkflowStep label="Temperature probe" status="PASSED" /><WorkflowStep label="Profile loaded" status="PASSED" /></div><button className="start-button"><Zap size={17} fill="currentColor" /> Start simulation</button></div><div className="timeline-board"><div className="board-title"><span>Event timeline</span><span>deterministic / seed 0143</span></div><Timeline label="PRECHECK_PASSED" time="14:31:52.042" /><Timeline label="SOFT_START" time="14:31:52.090" /><Timeline label="TARGET_REACHED" time="14:31:52.410" /><Timeline label="TRIP_DETECTED" time="waiting" muted /></div></div>; }
function HistoryView() { return <div className="data-board"><div className="filter-row"><span>1284 sessions</span><button className="filter-control">All verdicts</button><button className="filter-control">Last 30 days</button><button className="filter-control">Batch / serial</button></div><div className="data-table"><div className="data-row data-head"><span>Test ID</span><span>Unit</span><span>Batch</span><span>Profile</span><span>Trip time</span><span>Result</span></div>{[["TST-2605-0142", "Acti9 iC60N / 16A", "B-2609", "1.45 × In", "188 ms", "PASS"], ["TST-2605-0141", "S200M / 20A", "B-2609", "2.55 × In", "72 ms", "PASS"], ["TST-2605-0140", "5SL6 / 32A", "B-2609", "1.45 × In", "NO TRIP", "FAIL"], ["TST-2605-0139", "Acti9 iC60N / 16A", "B-2608", "1.13 × In", "NO TRIP", "FAIL"]].map((row) => <div className="data-row" key={row[0]}>{row.map((value, index) => <span className={index === 0 ? "mono" : index === 5 ? `table-verdict ${value === "PASS" ? "green-text" : "orange-text"}` : ""} key={value}>{index === 5 && value === "PASS" ? <Check size={12} /> : null}{value}</span>)}</div>)}</div></div>; }
function CatalogView() { return <div className="catalog-grid"><CatalogItem manufacturer="Schneider Electric" model="Acti9 iC60N" rating="16A" curve="C" profiles="3 active profiles" /><CatalogItem manufacturer="ABB" model="S200M" rating="20A" curve="B" profiles="2 active profiles" /><CatalogItem manufacturer="Siemens" model="5SL6" rating="32A" curve="D" profiles="4 active profiles" /><div className="catalog-add"><span>+</span><strong>Add MCB model</strong><small>Admin permission required</small></div></div>; }
function ReportsView() { return <div className="report-grid"><ReportItem id="RPT-2605-0142" title="Acti9 iC60N / 16A" detail="PASS · generated 8 min ago" /><ReportItem id="RPT-2605-0141" title="S200M / 20A" detail="PASS · generated 24 min ago" /><ReportItem id="RPT-2605-0138" title="Batch B-2609 summary" detail="12 sessions · generated yesterday" /></div>; }
function AnalyticsView() { return <div className="analytics-grid"><div className="analytics-hero"><span>Pass rate / 30d</span><strong>90.97%</strong><small><span className="green-text">+2.4%</span> from prior period</small><div className="analytics-bars"><i style={{ height: "42%" }} /><i style={{ height: "58%" }} /><i style={{ height: "52%" }} /><i style={{ height: "71%" }} /><i style={{ height: "64%" }} /><i style={{ height: "83%" }} /><i style={{ height: "91%" }} /></div></div><div className="analytics-list"><AnalyticsStat icon={<Clock3 size={16} />} label="Mean trip latency" value="174.2 ms" note="-6.8 ms / month" /><AnalyticsStat icon={<Gauge size={16} />} label="Most tested curve" value="C curve" note="684 sessions" /><AnalyticsStat icon={<Thermometer size={16} />} label="Thermal outliers" value="11 units" note="0.86% of sessions" /></div></div>; }
function AlertsView() { return <div className="alert-list"><AlertItem icon={<Thermometer size={16} />} title="Temperature probe drift detected" detail="Device / ESP32 · calibration check recommended before the next live test" severity="WARNING" /><AlertItem icon={<Clock3 size={16} />} title="Delayed trip pattern" detail="5SL6 / 32A · repeated in batch B-2609" severity="OPEN" /><AlertItem icon={<ShieldCheck size={16} />} title="Safety interlock ready" detail="Bench 01 · clear to enter ARMED state" severity="INFO" /></div>; }
function InspectorView() { return <div className="inspector-grid"><div className="anomaly-score"><span>Anomaly score</span><strong>0.78</strong><div className="score-track"><i /></div><small>marginal thermal signature</small></div><div className="evidence-board"><div className="board-title"><span>Evidence / SIM-0140</span><span>advisory only</span></div><Evidence label="Trip latency" observed="412 ms" expected="≤ 250 ms" /><Evidence label="Temperature slope" observed="+4.8 °C / 10m" expected="+2.1 °C / 10m" /><Evidence label="Current stability" observed="96.2%" expected="≥ 98.0%" /><p className="inspector-note">Trip occurred later than the configured envelope and terminal temperature rose faster than the batch median.</p></div></div>; }
function DeviceView() { return <div className="device-grid"><div className="device-hero"><div className="device-icon-large"><Cpu size={24} /></div><div><span>Gateway</span><h3>ESP32-TEST-01</h3><p>192.168.4.21 · firmware 0.8.4</p></div><strong className="green-text">ONLINE</strong></div><div className="sensor-list"><Sensor label="Current sensor / shunt" value="HEALTHY" reading="23.2 A" /><Sensor label="Terminal temperature" value="HEALTHY" reading="42.1 °C" /><Sensor label="Contact state" value="READY" reading="CLOSED" /><Sensor label="Safety interlock" value="READY" reading="CLOSED" /></div></div>; }

function WorkflowStep({ label, status }: { label: string; status: string }) { return <div className="workflow-step"><span><Check size={12} />{label}</span><strong>{status}</strong></div>; }
function Timeline({ label, time, muted }: { label: string; time: string; muted?: boolean }) { return <div className={`timeline ${muted ? "muted" : ""}`}><span className="timeline-dot" /><strong>{label}</strong><small>{time}</small></div>; }
function CatalogItem({ manufacturer, model, rating, curve, profiles }: { manufacturer: string; model: string; rating: string; curve: string; profiles: string }) { return <div className="catalog-item"><span>{manufacturer}</span><h3>{model}</h3><div><strong>{rating}</strong><b>{curve}</b></div><small>{profiles}</small></div>; }
function ReportItem({ id, title, detail }: { id: string; title: string; detail: string }) { return <div className="report-item"><FileCheck2 size={19} /><div><span>{id}</span><strong>{title}</strong><small>{detail}</small></div><button className="icon-action" aria-label={`Download ${id}`}><Download size={16} /></button></div>; }
function AnalyticsStat({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) { return <div className="analytics-stat"><span className="analytics-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></div>; }
function AlertItem({ icon, title, detail, severity }: { icon: React.ReactNode; title: string; detail: string; severity: string }) { return <div className="alert-item"><span className="alert-symbol">{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><b>{severity}</b></div>; }
function Evidence({ label, observed, expected }: { label: string; observed: string; expected: string }) { return <div className="evidence"><span>{label}</span><strong>{observed}</strong><small>{expected}</small></div>; }
function Sensor({ label, value, reading }: { label: string; value: string; reading: string }) { return <div className="sensor"><span className="sensor-dot" /><div><strong>{label}</strong><small>{reading}</small></div><b>{value}</b></div>; }